### ISSUE TITLE
Update on TMS

### ISSUE THREAD

**Issue by kamalkhnl** [niravcodes/TMSCaptchaAutoFiller#2]
Looks like there was update on TMS yesterday. The extension does not seem to work.

**Comment by niravcodes** [comment]
It's still working for me so far. 

The one case in which this doesn't work is if TMS logs you out with a `SESSION TIMED OUT` message. In that case just refresh the page. 

The extension also doesn't work in incognito mode, which might be what you experienced.

There might be some problem on your end. Did you recently add some new extensions to chrome?

**Comment by kamalkhnl** [comment]
> It's still working for me so far.
> 
> The one case in which this doesn't work is if TMS logs you out with a `SESSION TIMED OUT` message. In that case just refresh the page.
> 
> The extension also doesn't work in incognito mode, which might be what you experienced.
> 
> There might be some problem on your end. Did you recently add some new extensions to chrome?

This is not working for me in regular login page which it was 2 days ago.
Neither I am using incognito mode nor did I add any extensions recently.
 There was a client update recently I think and Multiple people are reporting same thing in extension reviews.  Looks like I am not alone.

**Comment by niravcodes** [comment]
cool. seems that some broker websites have changed their captcha implementations (and the font too!) It seems like it's still a browser based solution so it could still be reverse engineered, but maybe some other day...

Mine still works (tms01) so until they change it, you're on your own lol

**Comment by kamalkhnl** [comment]
lol. In case you want to check, it doesn't work on tms03.
